kind: Deployment
apiVersion: apps/v1
metadata:
  name: mysql
  namespace: expense
  labels:
    app: mysql
    tier: mysql
    project: expense
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
      tier: mysql
      project: expense
  template:
    metadata:
      labels:
         app: mysql
         tier: mysql
         project: expense
    spec:
      containers:
      - name: mysql
        image: sudhanaga1002/mysql:1.0.0 
---
kind: Service
apiVersion: v1
metadata:
  name: mysql
spec:
  selector: #labels are used as selectors
    app: mysql
    tier: mysql
    project: expense
  ports:
  - protocol: TCP
    port: 3306 #service port port exposed inside the cluster, Port exposed by the Service (what clients see).
    targetPort: 3306 # port on the pod/container where app is runnung